# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/python

trigger:
- master
- release-*

jobs:

- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - bash: >
      conda create --yes --quiet --name tike
      python=$(python.version)
      conda-build
      conda-verify
      pycodestyle
      pydocstyle
    displayName: Create Anaconda environment
  - bash: |
      conda activate tike
      pycodestyle --count -v .
    displayName: Run python code linter
  - bash: |
      conda activate tike
      pydocstyle --match='(?!utils).*\.py' --count -v src/tike/
    displayName: Run python docstring linter
  - bash: |
      conda activate tike
      conda build . --no-anaconda-upload -c conda-forge
    displayName: Conda build

- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 4
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
# On Hosted macOS, the agent user doesn't have ownership of Miniconda's
# installation directory. We need to take ownership if we want to update
# conda or install packages globally
  # - bash: sudo chown -R $USER $CONDA
  #     displayName: Take ownership of conda installation
  - bash: >
      conda create --yes --quiet --name tike
      python=$(python.version)
      conda-build
      conda-verify
    displayName: Create Anaconda environment
  - bash: |
      conda activate tike
      conda build . --no-anaconda-upload -c conda-forge
    displayName: Conda build

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 4
  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  - bash: >
      conda create --yes --quiet --name tike
      python=$(python.version)
      conda-build
      conda-verify
    displayName: Create Anaconda environment
  - bash: |
      conda activate tike
      conda build . --no-anaconda-upload -c conda-forge
    displayName: Conda build
