package:
  name: tike
  version: alpha

source:
  path: .

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed
      --no-cache-dir --no-binary :all: -vvv"

requirements:
  host:
    - pip
    - python={{ python }}
    - setuptools_scm
  run:
    - matplotlib-base
    - mpi4py
    - numpy
    - python={{ python }}
    - setuptools

test:
  requires:
    - nose
    - coverage
  imports:
    - tike
  source_files:
    - tests/*
  commands:
    - nosetests --config=setup.cfg

app:
    own_environment: True

about:
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
