package:
  name: tike
  version: alpha

source:
  path: .

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
  host:
    - Make  # [win]
    - MinGW  # [win]
    - pip
    - python={{ python }}
    - scikit-build
    - setuptools
    - setuptools_scm
  run:
    - futures  # [py2k]
    - numpy
    - matplotlib
    - openmp
    - 'pillow>5.2'  # [win]
    - python={{ python }}
    - six
    - 'tomopy>=1.2'

test:
  requires:
    - nose
  imports:
    - tike
  source_files:
    - test*
  commands:
    - nosetests

app:
    own_environment: True

about:
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
