package:
  name: tike
  version: alpha

source:
  path: .

build:
  number: 0
  script:
    - "set CMAKE_GENERATOR=Ninja"  # [win]
    - "export CMAKE_GENERATOR=Ninja"  # [not win]
    - "set CC=cl"  # [win]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed
      --no-cache-dir --no-binary :all: -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python={{ python }}
    - scikit-build
    - setuptools_scm
  run:
    - numpy
    - matplotlib
    - openmp
    - python={{ python }}
    - six
    - 'tomopy>=1.2'

test:
  requires:
    - nose
  imports:
    - tike
  source_files:
    - test*
  commands:
    - nosetests

app:
    own_environment: True

about:
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
